services:
  server:
    build:
      context: .
      args:
        - PORT=${API_PORT}
    restart: unless-stopped
    environment:
      - PORT=${API_PORT}
    ports:
      - 127.0.0.1:${API_PORT}:${API_PORT}
